const canvas = document.getElementById('worldCanvas');
const ctx = canvas.getContext('2d');
const COLS = 32;
const ROWS = 24;
const CELL = 16;
const materials = [
  { name: 'Moosgras', detail: 'Natürlich · Stapel 64', base: '#759b4c', accent: '#a9c665', dark: '#4d713a' },
  { name: 'Lehm', detail: 'Erde · Stapel 64', base: '#a56845', accent: '#c5875b', dark: '#704333' },
  { name: 'Sand', detail: 'Natürlich · Stapel 64', base: '#d8bb77', accent: '#edd49a', dark: '#b19158' },
  { name: 'Stein', detail: 'Mineral · Stapel 64', base: '#7f8b88', accent: '#aab1a8', dark: '#596662' },
  { name: 'Holz', detail: 'Baumaterial · Stapel 32', base: '#996642', accent: '#c08a5c', dark: '#6e432f' },
  { name: 'Kohle', detail: 'Erz · Stapel 16', base: '#3d4845', accent: '#68716b', dark: '#242d2a' }
];
let selected = 0;
let world = [];
const keys = new Set();
const player = { x: 8.5, y: 12, vy: 0, grounded: false };
const noise = (x, y, salt = 0) => Math.abs(Math.sin(x * 12.9898 + y * 78.233 + salt * 37.11) * 43758.5453) % 1;
function createWorld() { world = Array.from({ length: ROWS }, (_, y) => Array.from({ length: COLS }, (_, x) => { const shoreline = 14 + Math.round(Math.sin(x / 4) * 1.8 + Math.sin(x / 8) * 2); if (y < shoreline) return -1; if (y === shoreline) return 0; if (y < shoreline + 3) return 1; return noise(x, y) > .82 ? 3 : 1; })); }
function resizeCanvas() { const box = canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; canvas.width = box.width * ratio; canvas.height = box.height * ratio; ctx.setTransform(ratio * box.width / (COLS * CELL), 0, 0, ratio * box.height / (ROWS * CELL), 0, 0); drawWorld(); }
function drawPixelTexture(x, y, type) { const material = materials[type]; ctx.fillStyle = material.base; ctx.fillRect(x, y, CELL, CELL); for (let py = 0; py < 4; py++) for (let px = 0; px < 4; px++) { const value = noise(x + px, y + py, type); if (value > .78) { ctx.fillStyle = material.accent; ctx.fillRect(x + px * 4, y + py * 4, 4, 4); } else if (value < .15) { ctx.fillStyle = material.dark; ctx.fillRect(x + px * 4, y + py * 4, 4, 4); } } ctx.strokeStyle = 'rgba(22,47,30,.13)'; ctx.lineWidth = .7; ctx.strokeRect(x, y, CELL, CELL); }
function drawPlayer() { const x = player.x * CELL; const y = player.y * CELL; ctx.fillStyle = '#f2c09a'; ctx.fillRect(x + 4, y - 13, 8, 7); ctx.fillStyle = '#263c34'; ctx.fillRect(x + 3, y - 15, 10, 4); ctx.fillStyle = '#d25c4f'; ctx.fillRect(x + 4, y - 6, 8, 7); ctx.fillStyle = '#405f4a'; ctx.fillRect(x + 3, y + 1, 4, 5); ctx.fillRect(x + 9, y + 1, 4, 5); }
function drawWorld() { ctx.clearRect(0, 0, COLS * CELL, ROWS * CELL); const sky = ctx.createLinearGradient(0, 0, 0, ROWS * CELL); sky.addColorStop(0, '#8fc6d5'); sky.addColorStop(.72, '#b5d8d4'); sky.addColorStop(1, '#e5e4b1'); ctx.fillStyle = sky; ctx.fillRect(0, 0, COLS * CELL, ROWS * CELL); ctx.fillStyle = 'rgba(255,247,196,.65)'; ctx.fillRect(4 * CELL, 3 * CELL, 4 * CELL, 2 * CELL); ctx.fillRect(23 * CELL, 6 * CELL, 3 * CELL, CELL); world.forEach((row, y) => row.forEach((type, x) => { if (type >= 0) drawPixelTexture(x * CELL, y * CELL, type); })); ctx.fillStyle = 'rgba(44,92,61,.5)'; for (let x = 0; x < COLS; x += 3) { const y = world[x] ? world.findIndex(v => v[x] >= 0) : -1; if (y > 0 && noise(x, 2) > .35) { ctx.fillRect(x * CELL + 5, y * CELL - 7, 3, 7); ctx.fillRect(x * CELL + 2, y * CELL - 5, 9, 3); } } drawPlayer(); }
function groundAt(x) { const column = Math.max(0, Math.min(COLS - 1, Math.floor(x))); return world.findIndex((row) => row[column] >= 0); }
function updatePlayer() { const left = keys.has('a') || keys.has('arrowleft'); const right = keys.has('d') || keys.has('arrowright'); const jump = keys.has(' ') || keys.has('w') || keys.has('arrowup'); if (left) player.x -= .08; if (right) player.x += .08; player.x = Math.max(.2, Math.min(COLS - 1.2, player.x)); if (jump && player.grounded) { player.vy = -.25; player.grounded = false; } player.vy += .012; player.y += player.vy; const ground = groundAt(player.x); if (ground >= 0 && player.y >= ground) { player.y = ground; player.vy = 0; player.grounded = true; } if (ground < 0) { player.y = Math.min(ROWS - 2, player.y); player.grounded = false; } document.getElementById('coordinates').textContent = `X ${String(Math.floor(player.x)).padStart(2, '0')} · Y ${String(Math.floor(player.y)).padStart(2, '0')} · Z 12`; drawWorld(); requestAnimationFrame(updatePlayer); }
function pixelPreview(material, size = 40) { const el = document.createElement('canvas'); el.width = size; el.height = size; const c = el.getContext('2d'); c.fillStyle = material.base; c.fillRect(0, 0, size, size); for (let py = 0; py < 8; py++) for (let px = 0; px < 8; px++) { c.fillStyle = noise(px, py, materials.indexOf(material)) > .72 ? material.accent : noise(px, py, 2) < .18 ? material.dark : material.base; c.fillRect(px * size / 8, py * size / 8, size / 8, size / 8); } return el.toDataURL(); }
function renderItems() { const inventory = document.getElementById('inventoryGrid'); const hotbar = document.getElementById('hotbar'); inventory.innerHTML = ''; hotbar.innerHTML = ''; materials.forEach((material, index) => { const image = pixelPreview(material); const cell = document.createElement('button'); cell.className = `inventory-cell${index === selected ? ' selected' : ''}`; cell.innerHTML = `<img class="pixel" src="${image}" alt="${material.name}"><span class="item-number">${index + 1}</span>`; cell.onclick = () => chooseMaterial(index); inventory.appendChild(cell); const slot = document.createElement('button'); slot.className = `hotbar-slot${index === selected ? ' active' : ''}`; slot.innerHTML = `<span>${index + 1}</span><img class="pixel" src="${image}" alt="${material.name}">`; slot.onclick = () => chooseMaterial(index); hotbar.appendChild(slot); }); updateSelected(); }
function chooseMaterial(index) { selected = index; renderItems(); }
function updateSelected() { const material = materials[selected]; document.getElementById('selectedName').textContent = material.name; document.getElementById('selectedDetail').textContent = material.detail; document.getElementById('selectedPreview').style.backgroundImage = `url(${pixelPreview(material, 42)})`; document.getElementById('selectedPreview').style.backgroundSize = 'cover'; }
function interact(event, place) { const rect = canvas.getBoundingClientRect(); const x = Math.floor((event.clientX - rect.left) / rect.width * COLS); const y = Math.floor((event.clientY - rect.top) / rect.height * ROWS); if (x < 0 || y < 0 || x >= COLS || y >= ROWS) return; if (place) { world[y][x] = selected; } else { world[y][x] = -1; } drawWorld(); document.getElementById('blockCount').textContent = `${world.flat().filter(v => v >= 0).length} BLÖCKE`; document.getElementById('coordinates').textContent = `X ${String(x).padStart(2, '0')} · Y ${String(y).padStart(2, '0')} · Z 12`; }
canvas.addEventListener('click', event => interact(event, false)); canvas.addEventListener('contextmenu', event => { event.preventDefault(); interact(event, true); }); document.addEventListener('keydown', event => { const key = event.key.toLowerCase(); if ([' ', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright', 'a', 'd', 'w', 's'].includes(key)) { keys.add(key); event.preventDefault(); } const number = Number(event.key); if (number >= 1 && number <= materials.length) chooseMaterial(number - 1); }); document.addEventListener('keyup', event => keys.delete(event.key.toLowerCase())); document.getElementById('resetWorld').onclick = () => { createWorld(); player.x = 8.5; player.y = 12; player.vy = 0; drawWorld(); document.getElementById('blockCount').textContent = `${world.flat().filter(v => v >= 0).length} BLÖCKE`; }; createWorld(); renderItems(); window.addEventListener('resize', resizeCanvas); resizeCanvas(); updatePlayer();
